name: Deploy via git-ftp
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: git-ftp-action
      uses: gabrielsevigny/FTP-Deploy-Action@3.1.1
      with:
        url: "ftp://gabrielsevigny.com/public_html/gittest/"
        user: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PWD }}
