name: Deploy via git-ftp
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: git-ftp-action
      uses: sebastianpopp/git-ftp-action@3.0.0
      with:
        action: "push"
        url: "ftp://gabrielsevigny.com/public_html/gittest/"
        user: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PWD }}
